export const thinkingPhrases = [
  "Thinking...",
  "Untangling your reminder...",
  "Polishing the details...",
  "Translating human into reminder...",
  "Asking the tiny reminder goblin...",
  "Shuffling the dates around...",
  "Looking for the important bit...",
  "Turning that into something useful...",
  "Giving it a quick think...",
  "Putting the pieces together...",
  "Consulting the calendar spirits...",
  "Tidying up the reminder text...",
  "Checking what you probably meant...",
  "Cooking up a neat reminder...",
  "Finding the when in the what...",
  "Doing the date math...",
  "Reading between the lines...",
  "Making sense of that message...",
  "Converting chaos into structure...",
  "One moment while I squint at this...",
  "Listening for the hidden deadline...",
  "Packing this into reminder form...",
  "Getting the details in order...",
  "Giving your note a second brain...",
  "Hunting for a due date...",
  "Trying not to overthink it...",
  "Turning that into future-you help...",
  "Lining up the title and timing...",
  "Giving it a tidy interpretation...",
  "Peeking at the schedule dimension...",
  "Formatting your future memory...",
  "Making the reminder less forgettable...",
  "Sorting the signal from the noise...",
  "Giving your message a little structure...",
  "Doing a quick sanity check...",
  "Trying to be appropriately helpful...",
  "Finding the reminder hiding in there...",
  "Looking for clues...",
  "Making it reminder-shaped...",
  "Running the tiny planner engine...",
  "Connecting the dots...",
  "Wrapping this into a to-do for future you...",
  "Taking a thoughtful pause...",
  "Extracting the useful bits...",
  "Whispering to the date parser...",
  "Giving your note a glow-up...",
  "Finding out what matters most...",
  "Reducing ambiguity with style...",
  "Organizing the mayhem...",
  "Sharpening the reminder...",
];

export function getRandomThinkingPhrase() {
  return thinkingPhrases[Math.floor(Math.random() * thinkingPhrases.length)] ?? "Thinking...";
}
